// source: data_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.simpledata.RecordsResponse');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.simpledata.Record');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.simpledata.RecordsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.simpledata.RecordsResponse.repeatedFields_, null);
};
goog.inherits(proto.simpledata.RecordsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.simpledata.RecordsResponse.displayName = 'proto.simpledata.RecordsResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.simpledata.RecordsResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.simpledata.RecordsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.simpledata.RecordsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.simpledata.RecordsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.simpledata.RecordsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
recordsList: jspb.Message.toObjectList(msg.getRecordsList(),
    proto.simpledata.Record.toObject, includeInstance),
totalAvailable: jspb.Message.getFieldWithDefault(msg, 2, 0),
returnedCount: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.simpledata.RecordsResponse}
 */
proto.simpledata.RecordsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.simpledata.RecordsResponse;
  return proto.simpledata.RecordsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.simpledata.RecordsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.simpledata.RecordsResponse}
 */
proto.simpledata.RecordsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.simpledata.Record;
      reader.readMessage(value,proto.simpledata.Record.deserializeBinaryFromReader);
      msg.addRecords(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTotalAvailable(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setReturnedCount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.simpledata.RecordsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.simpledata.RecordsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.simpledata.RecordsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.simpledata.RecordsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRecordsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.simpledata.Record.serializeBinaryToWriter
    );
  }
  f = message.getTotalAvailable();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getReturnedCount();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * repeated Record records = 1;
 * @return {!Array<!proto.simpledata.Record>}
 */
proto.simpledata.RecordsResponse.prototype.getRecordsList = function() {
  return /** @type{!Array<!proto.simpledata.Record>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.simpledata.Record, 1));
};


/**
 * @param {!Array<!proto.simpledata.Record>} value
 * @return {!proto.simpledata.RecordsResponse} returns this
*/
proto.simpledata.RecordsResponse.prototype.setRecordsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.simpledata.Record=} opt_value
 * @param {number=} opt_index
 * @return {!proto.simpledata.Record}
 */
proto.simpledata.RecordsResponse.prototype.addRecords = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.simpledata.Record, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.simpledata.RecordsResponse} returns this
 */
proto.simpledata.RecordsResponse.prototype.clearRecordsList = function() {
  return this.setRecordsList([]);
};


/**
 * optional int32 total_available = 2;
 * @return {number}
 */
proto.simpledata.RecordsResponse.prototype.getTotalAvailable = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.simpledata.RecordsResponse} returns this
 */
proto.simpledata.RecordsResponse.prototype.setTotalAvailable = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 returned_count = 3;
 * @return {number}
 */
proto.simpledata.RecordsResponse.prototype.getReturnedCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.simpledata.RecordsResponse} returns this
 */
proto.simpledata.RecordsResponse.prototype.setReturnedCount = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


