# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'data_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64\x61ta_service.proto\x12\nsimpledata\"\x12\n\x10LargeDataRequest\"\x1d\n\rLargeDataLine\x12\x0c\n\x04line\x18\x01 \x01(\t\"U\n\x06Record\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x12\n\ndepartment\x18\x04 \x01(\t\x12\x0e\n\x06salary\x18\x05 \x01(\x01\"?\n\x0eRecordsRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\x12\x0e\n\x06\x66ilter\x18\x03 \x01(\t\"g\n\x0fRecordsResponse\x12#\n\x07records\x18\x01 \x03(\x0b\x32\x12.simpledata.Record\x12\x17\n\x0ftotal_available\x18\x02 \x01(\x05\x12\x16\n\x0ereturned_count\x18\x03 \x01(\x05\x32\xac\x01\n\x11SimpleDataService\x12G\n\nGetRecords\x12\x1a.simpledata.RecordsRequest\x1a\x1b.simpledata.RecordsResponse\"\x00\x12N\n\x0fStreamLargeData\x12\x1c.simpledata.LargeDataRequest\x1a\x19.simpledata.LargeDataLine\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LARGEDATAREQUEST']._serialized_start=34
  _globals['_LARGEDATAREQUEST']._serialized_end=52
  _globals['_LARGEDATALINE']._serialized_start=54
  _globals['_LARGEDATALINE']._serialized_end=83
  _globals['_RECORD']._serialized_start=85
  _globals['_RECORD']._serialized_end=170
  _globals['_RECORDSREQUEST']._serialized_start=172
  _globals['_RECORDSREQUEST']._serialized_end=235
  _globals['_RECORDSRESPONSE']._serialized_start=237
  _globals['_RECORDSRESPONSE']._serialized_end=340
  _globals['_SIMPLEDATASERVICE']._serialized_start=343
  _globals['_SIMPLEDATASERVICE']._serialized_end=515
# @@protoc_insertion_point(module_scope)
